[package]
name = "r2-photo-api"
version = "0.4.2"
edition = "2024"
authors = ["Jeffery D. Mitchell", "<crusty.rustacean@gmail.com>"]
description = "A photo management API using Actix Web, SQLite, and Cloudflare R2"
readme = "README.md"
repository = "https://github.com/crustyrustacean/actix-web-starter.git"
license = "MIT"
publish = false

[[bin]]
name = "r2-photo-api"
path = "src/bin/main.rs"

[dependencies]
actix-multipart = { version = "0.8.0", features = ["tempfile"] }
actix-web = "4.14.0"
async-trait = "0.1.89"
anyhow = "1.0.103"
bytes = "1.12.0"
dotenvy = "0.15.7"
chrono = { version = "0.4.44", default-features = false, features = ["clock"] }
config = { version = "0.15.25", default-features = false, features = ["yaml"] }
heic = "0.1.6"
image = "0.25.10"
kamadak-exif = "0.6.1"
log = "0.4.33"
opendal = { version = "0.57.0", features = ["services-s3", "services-fs"] }
reqwest = { version = "0.13.2", features = [ "json" ] }
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde-aux = "4.7.0"
serde_json = "1.0.149"
sqlx = { version = "0.9.0", default-features = false, features = [
    "runtime-tokio",
    "sqlite",
    "macros",
    "uuid",
    "chrono",
    "migrate",
] }
tera = { version = "2.1.0", features = ["fast", "glob_fs"] }
thiserror = "2.0.18"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.19"
tracing-actix-web = "0.7.22"
tracing-log = "0.2.0"
tracing-bunyan-formatter = "0.3.1"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
uuid = { version = "1.23.4", features = ["v4", "serde"] }

[dev-dependencies]
reqwest = { version = "0.13.2", features = [ "form", "multipart" ] }